### ISSUE TITLE
Battery life per charge?

### ISSUE THREAD

**Issue by neopostmodern** [PhiBabin/Redox-Lipo-Adapter#4]
Are there any experiences yet how far one gets on a single battery charge (assuming the mentioned 500mAh)? Would it make sense to bother with a larger battery?

**Comment by PhiBabin** [comment]
I charged my keyboard at the end of April and I have not charged since then. Last time I checked 2 weeks ago, it had 3.465V. So it's probably 6month between charge. I'm using a 500mAh battery with V1.0 of the board. The stepdown regulator is for 3.3V.

**Comment by neopostmodern** [comment]
That's a great result!
Maybe it could be added to the README?
