### ISSUE TITLE
Discrepency with BOM link / description

### ISSUE THREAD

**Issue by o-klp** [PhiBabin/Redox-Lipo-Adapter#5]
Thanks for putting this repo up and keeping split keyboards accessible

I noticed the [Bill of Materials](https://github.com/PhiBabin/Redox-Lipo-Adapter/blob/main/BUILD.md#bill-of-materials) lists C1, C4 and C5 as 50v-rated capacitors. But the included Digitkey link points to 25v-rated ones.

Is it safe to use the 25v ones for those connections? I assume the voltage is low enough here given the components, but don't know what USB C can top out at

**Comment by PhiBabin** [comment]
I don't think the voltage rating matter for this application. The USB charging only got up to 5V.
